### ISSUE TITLE
Next release 2.4.0 or 3.0.0

### ISSUE THREAD

**Issue by BendingBender** [jsoverson/preprocess#67]
@Frizi and @orionstein, I'd like to release the next version soon. However, I'm looking at the changelog and I have doubts as which version number I should give this release.

There are a number of changes that might subtly break existing setups (like hidden blocks and coffescript extensions). All in all I'm in doubt of whether to call it 2.4.0 or 3.0.0 .

What do you guys think?

**Comment by Spy-Seth** [comment]
Semver said: breaking change = new major :)

**Comment by BendingBender** [comment]
Yeah I know. In an ideal world, the changes that were introduced this time are not breaking. Each of them is an extension and if something breaks, then that's a bug. In an ideal world...

Now that I think of it, the new EOL handling might actually impose a break. Any thoughts?

**Comment by Spy-Seth** [comment]
Yes it's enough to justify a major I think. With in addition all the other change, this not a bad idea to go on a new major release.

**Comment by BendingBender** [comment]
Well, just to be sure that no production systems break, I'll release it as 3.0.0. There were just too many changes to be sure that they were not breaking.

**Comment by Frizi** [comment]
What about writing some more tests before actual release? I'm not convinced right now that everything works as expected and as fast as expected. Things might have slow down due to a lot more going on with block statements or a little bit more dynamic regex compilation.

I'm currently running it in quite large environment and see quite big variation across different files. Don't have much time to pinpoint the issue on live code though.

**Comment by BendingBender** [comment]
Yes, before the 3.0.0 release, I'd like to at least accomplish following tasks:
- port the test suite to mocha
- add some test coverage framework
- change the `srcDir` context attribute to be optional and default it to `cwd`
- make the lib throw an error if a file that has to be included/extended can not be found along with some option on the context to opt in to not throwing an error in such case
