### ISSUE TITLE
Will it support .jsx files?

### ISSUE THREAD

**Issue by gocreating** [jsoverson/preprocess#79]
both [`gulp-preprocess`](https://www.npmjs.com/package/gulp-preprocess) and [`preprocessify`](https://github.com/evanmuller/preprocessify) are using `preprocess`
but it seems it doesn't support `jsx` files
will preprocess support `jsx` in the future?

**Comment by BendingBender** [comment]
Well, if you're talking about React's `jsx`, then this is basically JavaScript with some inline XML. In this case you can use the newest version of the lib directly as is. You must however provide the

```js
options.type = 'js';
```
If you're using `gulp-preprocess` or `preprocessify`, you'll have to open an issue there so that they bump their dependencies and implement the pass-through of the new options.
